# PowerShell script to setup Android SDK path
# Run this script: .\setup-android-sdk.ps1

Write-Host "🔍 Detecting Android SDK location..." -ForegroundColor Cyan

# Common Android SDK locations on Windows
$possiblePaths = @(
    "$env:LOCALAPPDATA\Android\Sdk",
    "$env:USERPROFILE\AppData\Local\Android\Sdk",
    "C:\Android\Sdk",
    "$env:ANDROID_HOME",
    "$env:ANDROID_SDK_ROOT"
)

$sdkPath = $null

# Check if ANDROID_HOME is already set
if ($env:ANDROID_HOME) {
    if (Test-Path $env:ANDROID_HOME) {
        $sdkPath = $env:ANDROID_HOME
        Write-Host "✅ Found Android SDK via ANDROID_HOME: $sdkPath" -ForegroundColor Green
    }
}

# If not found, check common locations
if (-not $sdkPath) {
    foreach ($path in $possiblePaths) {
        if ($path -and (Test-Path $path)) {
            $sdkPath = $path
            Write-Host "✅ Found Android SDK at: $sdkPath" -ForegroundColor Green
            break
        }
    }
}

# If still not found, ask user
if (-not $sdkPath) {
    Write-Host "❌ Android SDK not found automatically." -ForegroundColor Red
    Write-Host ""
    Write-Host "Please provide your Android SDK path:" -ForegroundColor Yellow
    Write-Host "Common locations:" -ForegroundColor Yellow
    Write-Host "  - C:\Users\YourUsername\AppData\Local\Android\Sdk" -ForegroundColor Gray
    Write-Host "  - C:\Android\Sdk" -ForegroundColor Gray
    Write-Host ""
    $sdkPath = Read-Host "Enter Android SDK path"
    
    if (-not (Test-Path $sdkPath)) {
        Write-Host "❌ Path does not exist: $sdkPath" -ForegroundColor Red
        exit 1
    }
}

# Convert path to Gradle format (escape backslashes)
$gradlePath = $sdkPath -replace '\\', '\\'

# Create local.properties file
$localPropertiesPath = "android\local.properties"
$content = "## This file is automatically generated.`n"
$content += "## Do not modify this file -- YOUR CHANGES WILL BE ERASED!`n"
$content += "##`n"
$content += "sdk.dir=$gradlePath`n"

Set-Content -Path $localPropertiesPath -Value $content

Write-Host ""
Write-Host "✅ Created local.properties file!" -ForegroundColor Green
Write-Host "   SDK Path: $sdkPath" -ForegroundColor Gray
Write-Host "   File: $localPropertiesPath" -ForegroundColor Gray
Write-Host ""

# Optionally set ANDROID_HOME environment variable
Write-Host "Would you like to set ANDROID_HOME environment variable? (Y/N)" -ForegroundColor Yellow
$setEnv = Read-Host

if ($setEnv -eq 'Y' -or $setEnv -eq 'y') {
    # Set for current session
    $env:ANDROID_HOME = $sdkPath
    $env:ANDROID_SDK_ROOT = $sdkPath
    
    # Set permanently for user
    [System.Environment]::SetEnvironmentVariable("ANDROID_HOME", $sdkPath, "User")
    [System.Environment]::SetEnvironmentVariable("ANDROID_SDK_ROOT", $sdkPath, "User")
    
    Write-Host "✅ ANDROID_HOME set to: $sdkPath" -ForegroundColor Green
    Write-Host "   (You may need to restart your terminal for changes to take effect)" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "🎉 Setup complete! You can now run: npm run android" -ForegroundColor Green

