@echo off
REM Batch script to setup Android SDK path for Windows
REM Run this script: setup-android-sdk.bat

echo.
echo 🔍 Detecting Android SDK location...
echo.

REM Check if ANDROID_HOME is set
if defined ANDROID_HOME (
    if exist "%ANDROID_HOME%" (
        set SDK_PATH=%ANDROID_HOME%
        echo ✅ Found Android SDK via ANDROID_HOME: %SDK_PATH%
        goto :create_file
    )
)

REM Check common locations
set "SDK_PATH=%LOCALAPPDATA%\Android\Sdk"
if exist "%SDK_PATH%" (
    echo ✅ Found Android SDK at: %SDK_PATH%
    goto :create_file
)

set "SDK_PATH=%USERPROFILE%\AppData\Local\Android\Sdk"
if exist "%SDK_PATH%" (
    echo ✅ Found Android SDK at: %SDK_PATH%
    goto :create_file
)

set "SDK_PATH=C:\Android\Sdk"
if exist "%SDK_PATH%" (
    echo ✅ Found Android SDK at: %SDK_PATH%
    goto :create_file
)

REM If not found, ask user
echo ❌ Android SDK not found automatically.
echo.
echo Please provide your Android SDK path:
echo Common locations:
echo   - C:\Users\YourUsername\AppData\Local\Android\Sdk
echo   - C:\Android\Sdk
echo.
set /p SDK_PATH="Enter Android SDK path: "

if not exist "%SDK_PATH%" (
    echo ❌ Path does not exist: %SDK_PATH%
    pause
    exit /b 1
)

:create_file
REM Convert path to Gradle format (escape backslashes)
set "GRADLE_PATH=%SDK_PATH:\=\\%"

REM Create local.properties file
echo ## This file is automatically generated.> android\local.properties
echo ## Do not modify this file -- YOUR CHANGES WILL BE ERASED!>> android\local.properties
echo ##>> android\local.properties
echo sdk.dir=%GRADLE_PATH%>> android\local.properties

echo.
echo ✅ Created local.properties file!
echo    SDK Path: %SDK_PATH%
echo    File: android\local.properties
echo.

REM Optionally set ANDROID_HOME
set /p SET_ENV="Would you like to set ANDROID_HOME environment variable? (Y/N): "

if /i "%SET_ENV%"=="Y" (
    setx ANDROID_HOME "%SDK_PATH%"
    setx ANDROID_SDK_ROOT "%SDK_PATH%"
    set ANDROID_HOME=%SDK_PATH%
    set ANDROID_SDK_ROOT=%SDK_PATH%
    echo ✅ ANDROID_HOME set to: %SDK_PATH%
    echo    (You may need to restart your terminal for changes to take effect)
)

echo.
echo 🎉 Setup complete! You can now run: npm run android
echo.
pause

